"use client";

import Link from "next/link";
import {
  ArrowLeft,
  Brain,
  Beaker,
  Zap,
  Headphones,
  Volume2,
  BookOpen,
  ExternalLink,
  Lightbulb,
  Activity,
} from "lucide-react";

import { Button } from "@/components/ui/Button";
import { StatHighlight } from "@/components/science/StatHighlight";
import { StudyCard } from "@/components/science/StudyCard";
import { ClickTrainDiagram } from "@/components/science/ClickTrainDiagram";
import { BinauralBeatsDiagram } from "@/components/science/BinauralBeatsDiagram";

export default function SciencePage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      {/* Header */}
      <header className="flex items-center justify-between border-b border-gray-200 dark:border-gray-800 px-4 py-3">
        <div className="flex items-center gap-3">
          <Link href="/">
            <Button variant="ghost" size="sm">
              <ArrowLeft className="h-4 w-4" />
            </Button>
          </Link>
          <h1 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            The Science
          </h1>
        </div>
      </header>

      <main className="mx-auto max-w-2xl p-6 space-y-8">
        {/* The Theory Section */}
        <section>
          <div className="flex items-center gap-2 mb-4">
            <Brain className="h-5 w-5 text-green-600 dark:text-green-400" />
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100">
              The Theory
            </h2>
          </div>
          <div className="rounded-xl bg-gray-100 dark:bg-gray-800 p-4 space-y-3">
            <p className="text-gray-700 dark:text-gray-300">
              Forty-hertz (40-Hz) oscillations are high-frequency gamma
              brainwaves generated by synchronized neural network activity.
              These oscillations appear to be attenuated in the brains of
              Alzheimer&apos;s disease (AD) patients.
            </p>
            <p className="text-gray-700 dark:text-gray-300">
              Research pioneered by Tsai&apos;s group at MIT showed that 40-Hz
              sensory stimulation can induce gamma oscillations in the brain,
              which may:
            </p>
            <ul className="space-y-2 text-gray-700 dark:text-gray-300">
              <li className="flex items-start gap-2">
                <span className="text-green-500 mt-1">1.</span>
                <span>
                  <strong>Enhance glymphatic clearance</strong> - Increases
                  astrocyte aquaporin-4 polarization, enhances arterial
                  pulsatility, and dilates meningeal lymphatic vessels
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-green-500 mt-1">2.</span>
                <span>
                  <strong>Accelerate CSF flow</strong> - Promotes cerebrospinal
                  fluid influx into brain tissue and efflux of interstitial
                  fluid
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-green-500 mt-1">3.</span>
                <span>
                  <strong>Clear amyloid-beta</strong> - Enhanced fluid dynamics
                  help remove A&beta; proteins and other metabolic waste from
                  the brain
                </span>
              </li>
            </ul>
          </div>
        </section>

        {/* PNAS 2026 Study Section */}
        <section>
          <div className="flex items-center gap-2 mb-4">
            <Beaker className="h-5 w-5 text-green-600 dark:text-green-400" />
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100">
              PNAS 2026 Primate Study
            </h2>
          </div>
          <div className="rounded-xl bg-gray-100 dark:bg-gray-800 p-4 space-y-4">
            <p className="text-gray-700 dark:text-gray-300">
              A January 2026 study from the Kunming Institute of Zoology
              provided the first non-human primate evidence for 40-Hz auditory
              stimulation therapy. Published in the{" "}
              <em>Proceedings of the National Academy of Sciences</em>.
            </p>

            <div className="grid grid-cols-2 gap-4 py-4">
              <StatHighlight value="205%" label="Aβ42 increase in CSF" />
              <StatHighlight value="5+ weeks" label="Effect persistence" />
            </div>

            <div className="space-y-2 text-sm text-gray-600 dark:text-gray-400">
              <p>
                <strong>Subjects:</strong> Nine aged rhesus macaques (26-31
                years) with naturally-developed amyloid plaques
              </p>
              <p>
                <strong>Protocol:</strong> 1 hour of 40-Hz auditory stimulation
                daily for 7 consecutive days
              </p>
              <p>
                <strong>Significance:</strong> Unlike rodent studies where
                effects disappeared after 7 days, the elevated Aβ levels in
                primates persisted for more than 5 weeks
              </p>
            </div>

            <a
              href="https://www.pnas.org/doi/10.1073/pnas.2529565123"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 text-sm text-green-600 dark:text-green-400 hover:underline"
            >
              Read the full study
              <ExternalLink className="h-3 w-3" />
            </a>
          </div>
        </section>

        {/* Cognitive Enhancement Section */}
        <section>
          <div className="flex items-center gap-2 mb-4">
            <Lightbulb className="h-5 w-5 text-green-600 dark:text-green-400" />
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100">
              Cognitive Enhancement
            </h2>
          </div>
          <div className="space-y-4">
            <div className="rounded-xl bg-gray-100 dark:bg-gray-800 p-4">
              <h3 className="font-medium text-gray-900 dark:text-gray-100 mb-2">
                Gamma Waves & Peak Performance
              </h3>
              <p className="text-gray-700 dark:text-gray-300 mb-3">
                Gamma oscillations (30-80 Hz) are associated with:
              </p>
              <ul className="grid grid-cols-2 gap-2 text-sm text-gray-600 dark:text-gray-400">
                <li className="flex items-center gap-2">
                  <Zap className="h-3 w-3 text-amber-500" />
                  Heightened focus
                </li>
                <li className="flex items-center gap-2">
                  <Activity className="h-3 w-3 text-amber-500" />
                  Flow states
                </li>
                <li className="flex items-center gap-2">
                  <Brain className="h-3 w-3 text-amber-500" />
                  Enhanced working memory
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="h-3 w-3 text-amber-500" />
                  Cross-brain communication
                </li>
              </ul>
            </div>

            <StudyCard
              icon={BookOpen}
              title="Exploratory Pilot Study"
              description="40-Hz entrainment improved mood, memory, and cognition, with participants showing mean cognitive score improvements from 75% to 85%."
              link="https://pmc.ncbi.nlm.nih.gov/articles/PMC7683678/"
              linkText="View study"
            />

            <StudyCard
              icon={BookOpen}
              title="MIT GENUS Research"
              description="Gamma Entrainment Using Sensory Stimulation (GENUS) has shown benefits extending beyond Alzheimer's to general brain health."
              link="https://news.mit.edu/2025/evidence-40hz-gamma-stimulation-promotes-brain-health-expanding-0314"
              linkText="Learn more"
            />

            <div className="rounded-xl bg-gray-100 dark:bg-gray-800 p-4">
              <h3 className="font-medium text-gray-900 dark:text-gray-100 mb-2">
                How It May Enhance Focus
              </h3>
              <ol className="space-y-2 text-sm text-gray-600 dark:text-gray-400">
                <li className="flex items-start gap-2">
                  <span className="text-green-500">1.</span>
                  <span>
                    Neural synchronization increases across brain regions
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-500">2.</span>
                  <span>
                    Information binding improves - the brain more effectively
                    combines sensory inputs
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-500">3.</span>
                  <span>
                    Attentional resources are enhanced for demanding tasks
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-500">4.</span>
                  <span>
                    Default mode network activity may decrease, reducing
                    mind-wandering
                  </span>
                </li>
              </ol>
            </div>
          </div>
        </section>

        {/* Audio Modes Section */}
        <section>
          <div className="flex items-center gap-2 mb-4">
            <Volume2 className="h-5 w-5 text-green-600 dark:text-green-400" />
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100">
              Audio Modes
            </h2>
          </div>
          <div className="space-y-4">
            {/* Click Train */}
            <div className="rounded-xl bg-gray-100 dark:bg-gray-800 p-4 space-y-3">
              <div className="flex items-center gap-2">
                <Volume2 className="h-4 w-4 text-green-500" />
                <h3 className="font-medium text-gray-900 dark:text-gray-100">
                  Click Train (PNAS Study Protocol)
                </h3>
              </div>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                Replicates the exact auditory stimulus parameters from the PNAS
                2026 primate study: 1ms bursts of a 1kHz pure tone, repeated 40
                times per second.
              </p>
              <div className="grid grid-cols-2 gap-3 text-xs text-gray-600 dark:text-gray-400">
                <div>
                  <span className="text-gray-500">Tone:</span> 1000 Hz sine wave
                </div>
                <div>
                  <span className="text-gray-500">Burst:</span> 1ms duration
                </div>
                <div>
                  <span className="text-gray-500">Rate:</span> 40 Hz (every
                  25ms)
                </div>
                <div>
                  <span className="text-gray-500">Session:</span> Configurable
                </div>
              </div>
              <p className="text-xs text-green-600 dark:text-green-400">
                Best for: Research protocol replication, direct auditory
                stimulation
              </p>
            </div>

            <ClickTrainDiagram />

            {/* Binaural Beats */}
            <div className="rounded-xl bg-gray-100 dark:bg-gray-800 p-4 space-y-3">
              <div className="flex items-center gap-2">
                <Headphones className="h-4 w-4 text-cyan-500" />
                <h3 className="font-medium text-gray-900 dark:text-gray-100">
                  Binaural Beats (Cognitive Enhancement)
                </h3>
              </div>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                Uses the psychoacoustic phenomenon of binaural beats. Two
                slightly different frequencies are played to each ear, and your
                brain perceives a &quot;phantom&quot; beat at the frequency
                difference.
              </p>
              <div className="grid grid-cols-2 gap-3 text-xs text-gray-600 dark:text-gray-400">
                <div>
                  <span className="text-gray-500">Left ear:</span> 200 Hz
                </div>
                <div>
                  <span className="text-gray-500">Right ear:</span> 240 Hz
                </div>
                <div>
                  <span className="text-gray-500">Perceived:</span> 40 Hz beat
                </div>
                <div>
                  <span className="text-gray-500">Requires:</span> Stereo
                  headphones
                </div>
              </div>
              <p className="text-xs text-cyan-600 dark:text-cyan-400">
                Best for: Focus, flow states, meditation, cognitive enhancement
              </p>
            </div>

            <BinauralBeatsDiagram />

            {/* Mode Comparison */}
            <div className="rounded-xl bg-gray-100 dark:bg-gray-800 p-4">
              <h3 className="font-medium text-gray-900 dark:text-gray-100 mb-3">
                Which Mode Should I Use?
              </h3>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between text-gray-600 dark:text-gray-400">
                  <span>Following Alzheimer&apos;s protocol</span>
                  <span className="text-green-500">Click Train</span>
                </div>
                <div className="flex justify-between text-gray-600 dark:text-gray-400">
                  <span>Focus and deep work</span>
                  <span className="text-amber-500">Either</span>
                </div>
                <div className="flex justify-between text-gray-600 dark:text-gray-400">
                  <span>Cognitive enhancement</span>
                  <span className="text-cyan-500">Binaural Beats</span>
                </div>
                <div className="flex justify-between text-gray-600 dark:text-gray-400">
                  <span>No headphones available</span>
                  <span className="text-green-500">Click Train</span>
                </div>
                <div className="flex justify-between text-gray-600 dark:text-gray-400">
                  <span>Meditation/relaxation</span>
                  <span className="text-cyan-500">Binaural Beats</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* References Section */}
        <section>
          <div className="flex items-center gap-2 mb-4">
            <BookOpen className="h-5 w-5 text-green-600 dark:text-green-400" />
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100">
              References
            </h2>
          </div>
          <div className="rounded-xl bg-gray-100 dark:bg-gray-800 p-4 space-y-3">
            <p className="text-sm font-medium text-gray-600 dark:text-gray-400">
              Key Research Papers
            </p>
            <ul className="space-y-3 text-sm text-gray-700 dark:text-gray-300">
              <li>
                <a
                  href="https://www.pnas.org/doi/10.1073/pnas.2529565123"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-start gap-2 hover:text-green-500"
                >
                  <ExternalLink className="h-3 w-3 mt-1 shrink-0" />
                  <span>
                    Wang et al. (2026). Long-term effects of forty-hertz
                    auditory stimulation as a treatment of Alzheimer&apos;s
                    disease. <em>PNAS</em>
                  </span>
                </a>
              </li>
              <li>
                <a
                  href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7683678/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-start gap-2 hover:text-green-500"
                >
                  <ExternalLink className="h-3 w-3 mt-1 shrink-0" />
                  <span>
                    Carstensen et al. (2020). Gamma entrainment frequency
                    affects mood, memory and cognition.{" "}
                    <em>BMC Neuroscience</em>
                  </span>
                </a>
              </li>
              <li>
                <a
                  href="https://www.frontiersin.org/journals/aging-neuroscience/articles/10.3389/fnagi.2022.1010765/full"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-start gap-2 hover:text-green-500"
                >
                  <ExternalLink className="h-3 w-3 mt-1 shrink-0" />
                  <span>
                    Shen et al. (2022). Cognitive tasks propagate neural
                    entrainment in response to visual 40 Hz stimulation.{" "}
                    <em>Frontiers in Aging Neuroscience</em>
                  </span>
                </a>
              </li>
              <li>
                <a
                  href="https://www.nature.com/articles/nature20587"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-start gap-2 hover:text-green-500"
                >
                  <ExternalLink className="h-3 w-3 mt-1 shrink-0" />
                  <span>
                    Iaccarino et al. (2016). Gamma frequency entrainment
                    attenuates amyloid load and modifies microglia.{" "}
                    <em>Nature</em>
                  </span>
                </a>
              </li>
            </ul>
          </div>
        </section>

        {/* Disclaimer */}
        <section className="pb-8">
          <div className="rounded-xl border border-amber-300 dark:border-amber-700 bg-amber-50 dark:bg-amber-900/20 p-4">
            <p className="text-sm text-amber-800 dark:text-amber-200">
              <strong>Disclaimer:</strong> This app is for personal experimental
              use only. It is not a medical device and has not been evaluated by
              any regulatory agency. Do not use if you have epilepsy or other
              neurological conditions without consulting a healthcare
              professional.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
